//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutputStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutputStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VendingMachine.OutputStrings", typeof(OutputStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT BALANCE: $.
        /// </summary>
        internal static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To insert money, enter &apos;$&apos; followed by the currency value
        ///To select an item, enter item coordinates, i.e. &apos;A1&apos; (default range [A-D, 1-5]).
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSUFFICIENT FUNDS (${0}).
        /// </summary>
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0}.
        /// </summary>
        internal static string ItemCost {
            get {
                return ResourceManager.GetString("ItemCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- [DEBUG] Current Item Queue State ---
        ///Dispensing Item: {0}
        ///Flavor: {1}
        ///Wrapper Color: {2}
        ///Remaining in queue: {3}
        ///----------------------------------------.
        /// </summary>
        internal static string QueueStatus {
            get {
                return ResourceManager.GetString("QueueStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLD OUT.
        /// </summary>
        internal static string SoldOut {
            get {
                return ResourceManager.GetString("SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRASH COMPARTMENT EMPTY.
        /// </summary>
        internal static string TrashIsEmpty {
            get {
                return ResourceManager.GetString("TrashIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string TrashReport {
            get {
                return ResourceManager.GetString("TrashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------.
        /// </summary>
        internal static string TrashReportFooter {
            get {
                return ResourceManager.GetString("TrashReportFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- TRASH REPORT---.
        /// </summary>
        internal static string TrashReportHeader {
            get {
                return ResourceManager.GetString("TrashReportHeader", resourceCulture);
            }
        }
    }
}
